CREATE TABLE `V2_CUSTOMERS` (
  ID VARCHAR(127) PRIMARY KEY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  MIDDLE_NAME VARCHAR(255) DEFAULT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  SSN VARCHAR(9) NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  GENDER VARCHAR(255) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATION_ZONE_ID VARCHAR(255) NOT NULL,
  MODIFIED_AT TIMESTAMP NULL DEFAULT NULL,
  MODIFICATION_ZONE_ID VARCHAR(255) NULL DEFAULT NULL
);